language: ruby
addons:
  postgresql: "9.4"
rvm:
  - 2.2.1
before_install: gem install bundler -v 1.10.3
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp spec/config.travis.yml spec/config.yml
env:
  - REDSHIFT_ENV=test
